#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/amenity HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic


###
#  findOne
###
GET http://localhost:4000/api/v1/amenity/35bc8241-087b-4b6f-8104-5530125fb8ef HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic


###
# create
###
POST http://localhost:4000/api/v1/amenity  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic

{
    "type": "Small Bathroom",
    "description": "includes sink",
    "percentage": 30
}


###
# update
###
PUT http://localhost:4000/api/v1/amenity/35bc8241-087b-4b6f-8104-5530125fb8ef HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic


{
    "type": "Bathroom",
    "description": "includes sink"
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/amenity HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic

{
    "amenity_id": "35bc8241-087b-4b6f-8104-5530125fb8ef"
}