#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/amenity_room_type HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwMTk3MzA4LTdjYjYtNGI0Yy1hODJmLWYzN2I3ZjQ1MTc0YyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDgwNjMwLCJleHAiOjE2MjUwODc4MzB9.rziYUsYEH_b9MPEShu4Wn8cATg9oGnhYLR8Zkc3kcBM



###
#  findOne
###
GET http://localhost:4000/api/v1/amenity_room_type/462797a7-d5cb-4809-bb2f-6da06428bea2 HTTP/1.1
Content-Type: application/json


###
# create
###
POST http://localhost:4000/api/v1/amenity_room_type  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwMTk3MzA4LTdjYjYtNGI0Yy1hODJmLWYzN2I3ZjQ1MTc0YyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDgwNjMwLCJleHAiOjE2MjUwODc4MzB9.rziYUsYEH_b9MPEShu4Wn8cATg9oGnhYLR8Zkc3kcBM

{
    "amenity_id":"644f547c-32e0-4f1f-b4e3-008924c303ae",
    "room_type_id": "8cd0adf6-2479-4bed-9bf0-d03b3bfa4360"
}


###
# update
###
PUT http://localhost:4000/api/v1/amenity_room_type/Ab1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwMTk3MzA4LTdjYjYtNGI0Yy1hODJmLWYzN2I3ZjQ1MTc0YyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDgwNjMwLCJleHAiOjE2MjUwODc4MzB9.rziYUsYEH_b9MPEShu4Wn8cATg9oGnhYLR8Zkc3kcBM


{
    "room_type_id": "5"
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/amenity_room_type HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwMTk3MzA4LTdjYjYtNGI0Yy1hODJmLWYzN2I3ZjQ1MTc0YyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDgwNjMwLCJleHAiOjE2MjUwODc4MzB9.rziYUsYEH_b9MPEShu4Wn8cATg9oGnhYLR8Zkc3kcBM


{
    "amenity_room_type_id": "276d9ec1-89ce-4a34-8d54-9b0be4c8a005"
}