#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/amenity HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGI2NmIwLTk3NzgtNDM5YS05MjIzLWVkZGM1OGU0OGQxNiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE2MjQ2Mjk1NjgsImV4cCI6MTYyNDYzNjc2OH0.3ao5z6lSRRSy7SXdMKifkpIyPBGQWliRRI7rWJIcN4E


###
#  findOne
###
GET http://localhost:4000/api/v1/amenity/462797a7-d5cb-4809-bb2f-6da06428bea2 HTTP/1.1
Content-Type: application/json


###
# create
###
POST http://localhost:4000/api/v1/amenity  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGI2NmIwLTk3NzgtNDM5YS05MjIzLWVkZGM1OGU0OGQxNiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE2MjQ2Mjk1NjgsImV4cCI6MTYyNDYzNjc2OH0.3ao5z6lSRRSy7SXdMKifkpIyPBGQWliRRI7rWJIcN4E

{
    "type": "Small Bathroom",
    "description": "includes sink",
    "percentage": 30
}


###
# update
###
PUT http://localhost:4000/api/v1/amenity/747c3727-22c4-4e06-9081-0fe7f8cd2c30 HTTP/1.1
Content-Type: application/json

{
    "type": "Bathroom",
    "description": "includes sink",
    "updated_by": "1315dee3-cc8b-4ad1-80bd-ec1b54b2ca80"
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/amenity HTTP/1.1
Content-Type: application/json

{
    "amenity_id": "747c3727-22c4-4e06-9081-0fe7f8cd2c30"
}