#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/loyalty_point HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDQ5NTMzLCJleHAiOjE2MjUwNTY3MzN9.jKfkWPWTvvHOgwBjtUAMz-6miz1wx1IS1w3ievsBxB4

###
#  List
###
GET http://localhost:4000/api/v1/loyalty_point HTTP/1.1
Content-Type: application/json


###
#  findOne
###
GET http://localhost:4000/api/v1/loyalty_point/931a293d-dcd5-483e-aaaa-8f7d64369e65 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic


###
# create
###
POST http://localhost:4000/api/v1/loyalty_point  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhjNDI2NDU5LWM2ZWYtNGVmOC04NDhkLTAyYWIyMTFjYTkxYSIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDUxOTc2LCJleHAiOjE2MjUwNTkxNzZ9.sokFFzezCADoe8Pjh3xxKlDu3Tj6J9ghYQFXJYFdxgs

{
    "points": 140

}


###
# update
###
PUT http://localhost:4000/api/v1/loyalty_point/1edd2a6c-47f5-4c04-b184-2f6b97dd4389 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic

{
    "points": 100
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/loyalty_point HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTczNzY0LCJleHAiOjE2MjQ5ODA5NjR9.5kv2JFwbHf3pFS1lyf3AIYcWb833Q2rGe9MsSwuJkic

{
    "loyalty_point_id": "1edd2a6c-47f5-4c04-b184-2f6b97dd4389"
}