#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/loyalty_point_history HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIxMjEyM2JkLTFlYTUtNGMwMS04MDE0LTBhN2U4MDQwYTlmMiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE2MjcwODE5MTQsImV4cCI6MTYyNzA4OTExNH0.y8kQmZfhxWDZc3Xi40NCMs0ZsmjwGXLYLtFKyZgw0E0


###
#  findOne
###
GET http://localhost:4000/api/v1/loyalty_point_history/382d373a-57ad-409a-858c-99d27cd758d8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTgxMTE5LCJleHAiOjE2MjQ5ODgzMTl9.t-wFcJOUpmZgDbFMj3BaeGUw-tly6kN0EQCpxa2_EVk


###
# create
###
POST http://localhost:4000/api/v1/loyalty_point_history  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTgxMTE5LCJleHAiOjE2MjQ5ODgzMTl9.t-wFcJOUpmZgDbFMj3BaeGUw-tly6kN0EQCpxa2_EVk

{
    "type":"special",
    "points":3,
    "booking_id":"3f2f7a8f-d6bd-4b13-863b-d758ac7278fe"
}


###
# update
###
PUT http://localhost:4000/api/v1/loyalty_point_history/382d373a-57ad-409a-858c-99d27cd758d8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTgxMTE5LCJleHAiOjE2MjQ5ODgzMTl9.t-wFcJOUpmZgDbFMj3BaeGUw-tly6kN0EQCpxa2_EVk

{
    "type":"ordinary"
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/loyalty_point_history HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI0OTgxMTE5LCJleHAiOjE2MjQ5ODgzMTl9.t-wFcJOUpmZgDbFMj3BaeGUw-tly6kN0EQCpxa2_EVk

{
    "lp_history_id": "382d373a-57ad-409a-858c-99d27cd758d8"
}