#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/package HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDg2NDEwLTc4ZmMtNDBlZi05MjRlLTEwYjAzMjQ1YzlhMiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM1OTk0LCJleHAiOjE2MjUxNDMxOTR9.yuZzUJGLJHxw2rhpcZ-uo7BqX1lrQh1RZrWD081riU8


###
#  findOne
###
GET http://localhost:4000/api/v1/package/8ba02ccb-24b7-436e-b0dd-e3bf2a56fbf7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwMTk3MzA4LTdjYjYtNGI0Yy1hODJmLWYzN2I3ZjQ1MTc0YyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDgwNjMwLCJleHAiOjE2MjUwODc4MzB9.rziYUsYEH_b9MPEShu4Wn8cATg9oGnhYLR8Zkc3kcBM


###
# create
###
POST http://localhost:4000/api/v1/package  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDg2NDEwLTc4ZmMtNDBlZi05MjRlLTEwYjAzMjQ1YzlhMiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM1OTk0LCJleHAiOjE2MjUxNDMxOTR9.yuZzUJGLJHxw2rhpcZ-uo7BqX1lrQh1RZrWD081riU8

{
    "min_guest": 10,
    "max_guest": 20,
    "title":"Sample",
    "pricing_id":"387887c5-45b1-42c8-8808-f62c6301dcd8",
    "room_type_id": "fed23f77-7a67-4a25-ad2f-01df974d1322",
    "description":"private"
}


###
# update
###
PUT http://localhost:4000/api/v1/package/8ba02ccb-24b7-436e-b0dd-e3bf2a56fbf7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwMTk3MzA4LTdjYjYtNGI0Yy1hODJmLWYzN2I3ZjQ1MTc0YyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDgwNjMwLCJleHAiOjE2MjUwODc4MzB9.rziYUsYEH_b9MPEShu4Wn8cATg9oGnhYLR8Zkc3kcBM

{
    "min_guest": 10,
    "max_guest": 100

}


###
# destroy
###
DELETE http://localhost:4000/api/v1/package HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwMTk3MzA4LTdjYjYtNGI0Yy1hODJmLWYzN2I3ZjQ1MTc0YyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDgwNjMwLCJleHAiOjE2MjUwODc4MzB9.rziYUsYEH_b9MPEShu4Wn8cATg9oGnhYLR8Zkc3kcBM

{
    "package_id": "8ba02ccb-24b7-436e-b0dd-e3bf2a56fbf7"
}