#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/payment HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyOTk2ODE4LTY3YjUtNDA0NS1hZDc3LTIyNWYxMDg5ZDBmNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM5ODMyLCJleHAiOjE2MjUxNDcwMzJ9.c7jp6_sM3StjoRmvSiwP-s2WoUbYkrJ-MhKldv7Qxno


###
#  findOne
###
GET http://localhost:4000/api/v1/payment/8c02d06c-b847-469a-bbc6-ef04aeb3f9ac HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyOTk2ODE4LTY3YjUtNDA0NS1hZDc3LTIyNWYxMDg5ZDBmNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM5ODMyLCJleHAiOjE2MjUxNDcwMzJ9.c7jp6_sM3StjoRmvSiwP-s2WoUbYkrJ-MhKldv7Qxno


###
# create
###
POST http://localhost:4000/api/v1/payment  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyOTk2ODE4LTY3YjUtNDA0NS1hZDc3LTIyNWYxMDg5ZDBmNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM5ODMyLCJleHAiOjE2MjUxNDcwMzJ9.c7jp6_sM3StjoRmvSiwP-s2WoUbYkrJ-MhKldv7Qxno

{
    "booking_id": "55287236-3fc1-486a-8bcb-c0c95572f8de",
    "mode": "Online",
    "ref_no":"0912Ak12",
    "payment_type":"Online",
    "payment_status":"Accepted",
    "amount":5000,
    "tax_code":"435f3c6c-7537-4527-adb5-dbfc3fabd698",
    "pd_code":"6ff6d7a5-0a16-4629-b9ed-b9fad68341af"

}


###
# update
###
PUT http://localhost:4000/api/v1/payment/8c02d06c-b847-469a-bbc6-ef04aeb3f9ac HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyOTk2ODE4LTY3YjUtNDA0NS1hZDc3LTIyNWYxMDg5ZDBmNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM5ODMyLCJleHAiOjE2MjUxNDcwMzJ9.c7jp6_sM3StjoRmvSiwP-s2WoUbYkrJ-MhKldv7Qxno

{

    "mode": "Over the Counter"
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/payment HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyOTk2ODE4LTY3YjUtNDA0NS1hZDc3LTIyNWYxMDg5ZDBmNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM5ODMyLCJleHAiOjE2MjUxNDcwMzJ9.c7jp6_sM3StjoRmvSiwP-s2WoUbYkrJ-MhKldv7Qxno

{
    "payment_id": "8c02d06c-b847-469a-bbc6-ef04aeb3f9ac"
}