#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/rooms_reserved HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzMzgyOTcwLWIwYTMtNDc4My1hMDVhLTQzYzBlYmY4NWI4NiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1OTIyMDU2LCJleHAiOjE2MjU5MjkyNTZ9.t3UxCZtc0_pidaggaGMPbdqTeZIO31xo6pFmCHWJU7A


###
#  findOne
###
GET http://localhost:4000/api/v1/rooms_reserved/6254cffc-fb73-4415-937c-9cbf1b6e9e6c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDg2NDEwLTc4ZmMtNDBlZi05MjRlLTEwYjAzMjQ1YzlhMiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM1OTk0LCJleHAiOjE2MjUxNDMxOTR9.yuZzUJGLJHxw2rhpcZ-uo7BqX1lrQh1RZrWD081riU8


###
# create
###
POST http://localhost:4000/api/v1/rooms_reserved  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDg2NDEwLTc4ZmMtNDBlZi05MjRlLTEwYjAzMjQ1YzlhMiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM1OTk0LCJleHAiOjE2MjUxNDMxOTR9.yuZzUJGLJHxw2rhpcZ-uo7BqX1lrQh1RZrWD081riU8

{
    "booking_id": "1fd27070-3a98-4375-baf1-ea6ad1547829",
    "room_id": "6d5bbfa7-2590-455d-96a8-bd8a9754a1bb",
    "room_reserved_status":"Pending",
    "rate":10,
    "no_of_guest": 10,
    "no_of_nights":3,
    "date_from":"2020-09-09",
    "date_to":"2020-09-12",
    "package_id":"a82bba75-9a4f-43a3-a133-d23730dd8b31",
    "checkIn":"2020-09-09",
    "checkOut":"2020-09-12"

}


###
# update
###
PUT http://localhost:4000/api/v1/rooms_reserved/6254cffc-fb73-4415-937c-9cbf1b6e9e6c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDg2NDEwLTc4ZmMtNDBlZi05MjRlLTEwYjAzMjQ1YzlhMiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM1OTk0LCJleHAiOjE2MjUxNDMxOTR9.yuZzUJGLJHxw2rhpcZ-uo7BqX1lrQh1RZrWD081riU8

{

    "no_of_nights":4
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/rooms_reserved HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDg2NDEwLTc4ZmMtNDBlZi05MjRlLTEwYjAzMjQ1YzlhMiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTM1OTk0LCJleHAiOjE2MjUxNDMxOTR9.yuZzUJGLJHxw2rhpcZ-uo7BqX1lrQh1RZrWD081riU8

{
    "room_reserved_id": "6254cffc-fb73-4415-937c-9cbf1b6e9e6c"
}