#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/room HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzOThlMzg4LTRkZGItNGMxZi1hMGFkLTMzNjQyOTQ2M2Y0MiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTE3NDI0LCJleHAiOjE2MjUxMjQ2MjR9.lfXw1SbjmnAaW2KCS0ShkfXH17vIO7GZgTna_7Q7K-Q


###
#  findOne
###
GET http://localhost:4000/api/v1/room/3d3d66fa-4122-4960-b3d8-179c26b4e190 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzOThlMzg4LTRkZGItNGMxZi1hMGFkLTMzNjQyOTQ2M2Y0MiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTE3NDI0LCJleHAiOjE2MjUxMjQ2MjR9.lfXw1SbjmnAaW2KCS0ShkfXH17vIO7GZgTna_7Q7K-Q


###
# create
###
POST http://localhost:4000/api/v1/room  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzOThlMzg4LTRkZGItNGMxZi1hMGFkLTMzNjQyOTQ2M2Y0MiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTE3NDI0LCJleHAiOjE2MjUxMjQ2MjR9.lfXw1SbjmnAaW2KCS0ShkfXH17vIO7GZgTna_7Q7K-Q

{
    "room_type_id": "a33cb5a0-164f-4c6e-be44-2f3a93749bbe",
    "description": "awit",
    "min_guest": 1,
    "max_guest": 3,
    "pricing_id": "ac483b3b-0d50-49ff-8be0-427b73d66ad7",
    "room_status": "Available"
}


###
# update
###
PUT http://localhost:4000/api/v1/room/3d3d66fa-4122-4960-b3d8-179c26b4e190 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzOThlMzg4LTRkZGItNGMxZi1hMGFkLTMzNjQyOTQ2M2Y0MiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTE3NDI0LCJleHAiOjE2MjUxMjQ2MjR9.lfXw1SbjmnAaW2KCS0ShkfXH17vIO7GZgTna_7Q7K-Q

{

    "max_guest": 5
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/room HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzOThlMzg4LTRkZGItNGMxZi1hMGFkLTMzNjQyOTQ2M2Y0MiIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MTE3NDI0LCJleHAiOjE2MjUxMjQ2MjR9.lfXw1SbjmnAaW2KCS0ShkfXH17vIO7GZgTna_7Q7K-Q

{
    "room_id": "3d3d66fa-4122-4960-b3d8-179c26b4e190"
}