#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/room_type HTTP/1.1
Content-Type: application/json


###
#  findOne
###
GET http://localhost:4000/api/v1/room_type/5251c175-6ffe-4a1b-8c07-431e3c4b9c89 HTTP/1.1
Content-Type: application/json


###
# create
###
POST http://localhost:4000/api/v1/room_type  HTTP/1.1
Content-Type: application/json

{
    "min_guest": 5,
    "max_guest": 20,
    "pricing_id":"82a48423-30c6-462c-a5e7-e56de204a202",
    "type": "SPECIAL",
    "description":"private"
}


###
# update
###
PUT http://localhost:4000/api/v1/room_type/5251c175-6ffe-4a1b-8c07-431e3c4b9c89 HTTP/1.1
Content-Type: application/json

{
    "min_guest": 3,
    "max_guest": 25,
    "additional_guest": 10,
    "rate_additional": 3500
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/room_type HTTP/1.1
Content-Type: application/json

{
    "room_type_id":"5251c175-6ffe-4a1b-8c07-431e3c4b9c89"
}