#########################
#
# USER
#
#########################



###
#  findDataTable
###
GET http://localhost:4000/api/v1/user/dataTable HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

###
#  findAll
###
GET http://localhost:4000/api/v1/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlODY3NTZhLWMwZGMtNDE2NS04NmZmLWVjYWM3MmE1MzEyOCIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI2OTQ4NTc1LCJleHAiOjE2MjY5NTU3NzV9.jbnMVUBcH1xiMTh1wm7fw4Os1659mmtZxeLTnIegMcM

###
#  findOne
###
GET http://localhost:4000/api/v1/user/3518d5e1-a7ab-4b24-9278-4aa9e77cf1ee HTTP/1.1
Content-Type: application/json
Authorization: Bearer 


###
# create
###
POST http://localhost:4000/api/v1/user  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2NWI2ODBjLWU1NmYtNDAwMC05YWRhLWI5YjYyODcwNmU4ZiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE2MjY5NTg2ODksImV4cCI6MTYyNjk2NTg4OX0.V7f_YTBQhTFCRpYMNJVG4IrYkTz96KOs_-n-TDJ3Vc0

# {
#     "email": "admin@admin.com",
#     "password": "admin",
#     "user_type": "admin",
#     "isActive": true
# }


# {
#     "email": "customer@customer.com",
#     "password": "customer",
#     "user_type": "customer",
#     "isActive": true
# }


# {
#     "email": "helpdesk@helpdesk.com",
#     "password": "helpdesk",
#     "user_type": "helpdesk",
#     "isActive": true
# }


###
# update
###
PUT http://localhost:4000/api/v1/user/cc54d70a-775a-4b84-a1e2-5b96f0e20fd7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMyMTFmNTYzLWRmMzktNGNhZi04NmExLTEyZThkZDBjNmEzNyIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE2MjU2NjkxMzMsImV4cCI6MTYyNTY3NjMzM30.8LQIksaetpY4gwgwoAY84XOPLRl2xsGD0wc0DCAZCaA

{
    "password": "admin",
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM1MThkNWUxLWE3YWItNGIyNC05Mjc4LTRhYTllNzdjZjFlZSIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwidXNlcl90eXBlIjoiYWRtaW4iLCJpYXQiOjE2MjM3ODE2NTcsImV4cCI6MTYyMzc4ODg1N30.tKjFiVDDnh1nCXG_I0SOHrsnS54p51S0-0AR72NrzgM

{
    "id": "ad4f88e2-1e74-4228-9f7b-54fe29c52b06"
}