#########################
#
# USER
#
#########################


###
#  findAll
###
GET http://localhost:4000/api/v1/user_information HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDQ5NTMzLCJleHAiOjE2MjUwNTY3MzN9.jKfkWPWTvvHOgwBjtUAMz-6miz1wx1IS1w3ievsBxB4


###
#  findOne
###
GET http://localhost:4000/api/v1/user_information/8b587eb3-9820-4393-9e50-5e3a4614ce53 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDQ5NTMzLCJleHAiOjE2MjUwNTY3MzN9.jKfkWPWTvvHOgwBjtUAMz-6miz1wx1IS1w3ievsBxB4


###
# create
###
POST http://localhost:4000/api/v1/user_information  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDQ5NTMzLCJleHAiOjE2MjUwNTY3MzN9.jKfkWPWTvvHOgwBjtUAMz-6miz1wx1IS1w3ievsBxB4
Content-Type: application/json

{
    "email": "admin@admin.com",
    "firstname": "Bryon",
    "middle_name": "",
    "last_name": "Alindugan",
    "contact_no": "09201121990",
    "street1": "DLC III",
    "city1": "Bulacan",
    "zip1": "3200",
    "state1": "NCR",
    "country1": "Philippines",
    "street2": "",
    "city2": "",
    "zip2": "",
    "state2": "",
    "country2": "",
    "birth_date": "2019-09-09",
    "nationality": "Filipino",
    "photo_url": "a",
    "loyalty_point_id": "1edd2a6c-47f5-4c04-b184-2f6b97dd4389"
}


###
# update
###
PUT http://localhost:4000/api/v1/user_information/8b587eb3-9820-4393-9e50-5e3a4614ce53 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3ZmU1NDJkLTI3ZTQtNDk2OS05MmFhLWY0ZGFlOTI0MDUyNyIsImVtYWlsIjoiYWRtaW4zQGFkbWluLmNvbSIsInVzZXJfdHlwZSI6ImFkbWluIiwiaWF0IjoxNjI1MDQ5NTMzLCJleHAiOjE2MjUwNTY3MzN9.jKfkWPWTvvHOgwBjtUAMz-6miz1wx1IS1w3ievsBxB4

{
    "middle_name": "Bandelaria"
}


###
# destroy
###
DELETE http://localhost:4000/api/v1/user_information HTTP/1.1
Content-Type: application/json

{
    "id": "1315dee3-cc8b-4ad1-80bd-ec1b54b2ca80"
}